(G-CODE GENERATED BY FLATCAM v8.991 - www.flatcam.org - Version Date: 2019/12/27)

(Name: Drill06In)
(Type: G-code from Excellon)
(Units: IN)

(Created on Thursday, 26 June 2025 at 07:27)

(Feedrate: 2.0 in/min)
(Feedrate rapids 59.0551 in/min)

(Z_Cut: -0.077 in)
(Z_Move: 0.059 in)
(Z Toolchange: 0.5906 in)
(X,Y Toolchange: 0.0000, 0.0000 in)
(Z Start: None in)
(Z End: 2.5 in)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    0.2180 ...    2.1646  in)
(Y range:    0.2173 ...    1.6560  in)

(Spindle Speed: None RPM)
G20
G90
G94




G01 F2.00
G00 Z0.0590

M03
G00 X0.3031 Y0.7795
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.3934 Y0.3504
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.5904 Y0.3504
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.7874 Y0.3504
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.3031 Y0.9765
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.7321 Y1.6181
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X1.1890 Y1.6181
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X1.3860 Y1.6181
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.9291 Y1.6181
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.4450 Y1.6260
G01 Z-0.0770
G01 Z0
G00 Z0.0590
G00 X0.2480 Y1.6260
G01 Z-0.0770
G01 Z0
G00 Z0.0590
M05
G00 Z2.50
G00 X0.0 Y0.0

